### ISSUE TITLE
Use persistent configuration.

### ISSUE THREAD

**Issue by emskye96** [emskye96/chameleon-ng#1]
Re-compiling to change skins in _current year_? I'm thinking flat files in the same folder as the DLL, even using GetPrivateProfile* functions would be a massive step up. I wouldn't mind including some JSON library but if we can stick to WinAPI functions that would be a lot nicer.

**Comment by aixxe** [comment]
I'd **really** rather not use GetPrivateProfile functions if possible.

**Comment by aixxe** [comment]
Got something working with [this JSON library](https://github.com/nlohmann/json). Everything is in the 'configuration' branch, let me know what you think either here or in the pull request.

**Comment by emskye96** [comment]
With a few fixes the system proposed in #3 is perfect for our needs.
