### ISSUE TITLE
Implement Gloves

### ISSUE THREAD

**Issue by xxxsomethingxd** [emskye96/chameleon-ng#11]
is there a way to implement gloves changer?

**Comment by aixxe** [comment]
Sure, there's always a way. There's enough information on various forums to get everything up and running. If you check other projects like AimTux there's even full source code - although some changes will need to be made to work on Windows.

**Comment by xxxsomethingxd** [comment]
You will add this or no btw?

**Comment by aixxe** [comment]
We don't have any plans to do this right now.

**Comment by xxxsomethingxd** [comment]
I like the project, but I don't know C++, actually you could use imgui listbox on override items for choosing between knives
