### ISSUE TITLE
VAC Error (not ban)

### ISSUE THREAD

**Issue by notradger** [emskye96/chameleon-ng#12]
Was working great for months.. But now I get some sort of VAC error message..
[Popup Message Screen Capture](https://goo.gl/ObKKYU)

I'm not using any other hacks and using my own injector.. 

Page that pops up afterwards says:

> Modifying game files and/or in-game textures may cause this error.
 
> Please remove any custom textures, skin changers, or software that modifies game files and restart your computer. We also recommend verifying your game files after making these changes.

Am I the only one that's getting this?

**Comment by notradger** [comment]
I used the current version of chameleon-ng and it doesn't seem to be doing the above issue...  Ill close this issue if it doesn't show up today..

**Comment by notradger** [comment]
Yeah it works.. I was using an older version of chameleon-ng.. You can delete this issue.. sorry..

**Comment by notradger** [comment]
It happened again..

**Comment by aixxe** [comment]
I can't reproduce it and I haven't heard anyone else report this. The issue must be on your end.
