### ISSUE TITLE
ALT+TAB while chameleon-ng menu open

### ISSUE THREAD

**Issue by notradger** [emskye96/chameleon-ng#13]
I notice an issue if i have the chameleon menu open and i accidentally alt+tab out of csgo.. 
Bad things happen..  It doesn't alt tab out right... The CSGO window and chameleon menu are still on screen.. 

I've figured out a workaround when i do this by just alt+tabbing back, sometimes works.. or i have to ctrl+alt+del and go to task manager.. then alt+tab again or a few times.. then it gets it back to the csgo window..

Thought you guys would like to know.. :)

**Comment by aixxe** [comment]
The WndProc hook we use is anything but perfect. If someone wants to fix this I'll gladly accept a pull request but it's not a big enough issue to put time into right now.

**Comment by notradger** [comment]
Axxie, could you elaborate on what exactly is happening here?  Like should the wndproc be looking for a message that signals the window is losing focus and disable the imgui menu?

Renderer.cpp:

`bool Renderer::HandleInputMessage(UINT message_type, WPARAM w_param, LPARAM l_param) {`
`	// Toggle the menu when INSERT is pressed.`
`	if (message_type == WM_KEYUP && w_param == VK_INSERT)`
`		this->active = !this->active;`


Perhaps what ever that message type i would use to detect the ALT+TAB  then set **this->active = 0**
before it determines whether its supposed to call ImGui_ImplDX9_WndProcHandler() or not?
