### ISSUE TITLE
fix - ALT+TAB while chameleon is open 

### ISSUE THREAD

**Issue by notradger** [emskye96/chameleon-ng#14]
I think i figured out a fix to the crazyness that happens when you alt+tab out of csgo with the chameleon menu open. I logged all the wndproc messages while i alt+tabbed out and the 2nd msg was
**WM_NCACTIVATE**.  Below modification works for me.. Do you see anything wrong with this approach? 

In Renderer.cpp --> Renderer::HandleInputMessage();

```
bool Renderer::HandleInputMessage(UINT message_type, WPARAM w_param, LPARAM l_param) {
>>	// If alt+tab is detected, close chameleon menu to switch windows properly
>>	if (message_type == WM_NCACTIVATE && w_param == 0 ) {
>>		this->active = false;
>>	}

	// Toggle the menu when INSERT is pressed.
	if (message_type == WM_KEYUP && w_param == VK_INSERT)
		this->active = !this->active;

 
	// When the GUI is active ImGui can handle input by itself.
	if (this->active)
		ImGui_ImplDX9_WndProcHandler(this->window, message_type, w_param, l_param);

	return this->active;
}
```

**Comment by aixxe** [comment]
It looks good to me. Thanks for the report, I've added it in.
