### ISSUE TITLE
New CSGO Compiler

### ISSUE THREAD

**Issue by ghost** [emskye96/chameleon-ng#15]
Can you update the signatures to make the cheat work on the newest update?

**Comment by PsychoO1** [comment]
If you don't wanna wait for update - just use pattern way instead of virtual function for forceFullUpdate
`FindPattern("engine.dll", "\xA1\x00\x00\x00\x00\xB9\x00\x00\x00\x00\x56\xFF\x50\x14\x8B\x34\x85", "x????x????xxxxxxx")`  pattern for last update

**Comment by aixxe** [comment]
Should be fixed now.
