### ISSUE TITLE
Implement graphical user interface for configuration

### ISSUE THREAD

**Issue by emskye96** [emskye96/chameleon-ng#2]
I'm thinking ImGui, how about you?

Not much point in stopping at dynamic offsets and cleaner code, may as well go all the way.

**Comment by aixxe** [comment]
That's quite fine, after all the messing around with ImGui on Linux I'm about ready to make something practical with it. We'll have to pattern scan for the IDirect3DDevice9 pointer which shouldn't be an issue. We can hook EndScene and do all the drawing there, haven't actually tried it yet but it should be easy enough. I'll commit it to a separate branch when I get something working.

**Comment by emskye96** [comment]
Okay, thanks. Also no need to worry too much about configuration stuff just yet, the other issue is just there to discuss potential formats and so on. I don't expect the GUI to be loading or saving any time soon.

**Comment by aixxe** [comment]
Initial hook code is in. I'll get the rest done tomorrow.

**Comment by emskye96** [comment]
Well, that was easier than expected.
