### ISSUE TITLE
Crashes csgo.exe on exit..

### ISSUE THREAD

**Issue by notradger** [emskye96/chameleon-ng#7]
Works great, but i noticed when i exited out of csgo.. it crashes when this is loaded..

Thought you would like to know that.

**Comment by aixxe** [comment]
As a temporary workaround you can comment out the destructor in `vmthook.h` like so:

```
~VMTHook() {
	// *this->baseclass = this->original_vft;
};
```

**Comment by notradger** [comment]
I tried that and it still crashes.. Kinda acted weird one time on exit where i had to ctrl+alt+del to task manager to close csgo.. But.. I can live with that. Great program..
