### ISSUE TITLE
StatTrak Enhancement Idea

### ISSUE THREAD

**Issue by notradger** [emskye96/chameleon-ng#8]
I thought id throw it out there and see what you guys think..

How about a way to have it update the stattrak count locally for a weapon?

**Comment by iamtis** [comment]
It is only really able to update on a round basis because calling that many ForceUpdates would be crazy mid play, Unless someone has found the correct function for calling stattrak and it works with a modified gun/knife. (I have been working on this for a little while)

**Comment by aixxe** [comment]
Pretty much what @iamtis said.

The event hook already has most of the checks for when you kill a player, you'd only need to increment a counter there but it wouldn't update in real-time so we don't think it's worth pursuing right now.
