### ISSUE TITLE
VAC BAN? or VAC ERROR?

### ISSUE THREAD

**Issue by Garry050** [emskye96/chameleon-ng#9]
If you inject this DLL, will you get VAC BAN?
Or will VAC authentication error occur?
(Or will the result change with DLL Injector?)

sorry my bad english

**Comment by aixxe** [comment]
Maybe, I don't know if changing injectors would make a difference. There's no way to really know if it's detected until someone reports a ban with sufficient evidence.

**Comment by Garry050** [comment]
Yes, but it's Overwatch only.
However, since it is Injecting DLL like Internel Hack, there may be cases of VAC BAN.

I will purchase some accounts and test it.
